-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 16:39:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(30) NOT NULL,
  `hospital_name` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `location_name` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`),
  INDEX `user-pk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user-pk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`device_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`device_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`device_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`device` ;

CREATE TABLE IF NOT EXISTS `mydb`.`device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `device_name` VARCHAR(45) NULL,
  `device_type` INT NULL,
  `device_location` INT NULL,
  `device_threshold` VARCHAR(45) NULL,
  PRIMARY KEY (`device_id`),
  INDEX `location-fk_idx` (`device_location` ASC) VISIBLE,
  INDEX `device-fk_idx` (`device_type` ASC) VISIBLE,
  CONSTRAINT `location-fk`
    FOREIGN KEY (`device_location`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `device-fk`
    FOREIGN KEY (`device_type`)
    REFERENCES `mydb`.`device_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`records` ;

CREATE TABLE IF NOT EXISTS `mydb`.`records` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL,
  `record_timestamp` DATETIME NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  PRIMARY KEY (`record_id`),
  INDEX `records-pk_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `records-pk`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`device` (`device_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
